// Build step for Vercel (no dependencies).
// Copies the static site into dist/ and writes dist/config.js from
// environment variables, so keys never need to be committed.
//
//   CLERK_PUBLISHABLE_KEY, SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY
//
// Run locally with:  node scripts/build.mjs
import { copyFileSync, cpSync, existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "dist");
const SKIP = new Set(["config.js", "config.example.js"]);

rmSync(out, { recursive: true, force: true });
mkdirSync(out);

let copied = 0;
for (const name of readdirSync(root)) {
  if (!/\.(html|css|js|ico|png|svg|webmanifest|txt)$/.test(name) || SKIP.has(name)) continue;
  copyFileSync(join(root, name), join(out, name));
  copied++;
}

// Folders shipped as-is (default site photos, universities by country).
for (const dir of ["img", "data"]) {
  if (!existsSync(join(root, dir))) continue;
  cpSync(join(root, dir), join(out, dir), { recursive: true });
  copied += readdirSync(join(root, dir)).length;
}

const env = (k) => (process.env[k] || "").trim().replace(/^["']+|["']+$/g, "");
// Only the origin is wanted — people often paste ".../rest/v1/" or a dashboard link.
function supabaseOrigin(raw) {
  if (!raw) return "";
  const dash = /supabase\.com\/dashboard\/project\/([a-z0-9]+)/i.exec(raw);
  if (dash) return `https://${dash[1]}.supabase.co`;
  try { return new URL(raw).origin; } catch { return raw.replace(/\/+$/, ""); }
}
const config = {
  CLERK_PUBLISHABLE_KEY: env("CLERK_PUBLISHABLE_KEY") || env("NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"),
  SUPABASE_URL: supabaseOrigin(env("SUPABASE_URL") || env("NEXT_PUBLIC_SUPABASE_URL")),
  SUPABASE_PUBLISHABLE_KEY:
    env("SUPABASE_PUBLISHABLE_KEY") || env("SUPABASE_ANON_KEY") || env("NEXT_PUBLIC_SUPABASE_ANON_KEY"),
};

const missing = Object.entries(config).filter(([, v]) => !v).map(([k]) => k);
if (missing.length) {
  console.warn(`⚠  Missing environment variables: ${missing.join(", ")}.`);
  console.warn("   The site will deploy, but show a setup screen until they are set in Vercel.");
}
if (/^sk_/.test(config.CLERK_PUBLISHABLE_KEY) || /^sb_secret_/.test(config.SUPABASE_PUBLISHABLE_KEY)) {
  console.error("✖  A SECRET key was provided where a publishable key belongs. Refusing to build.");
  process.exit(1);
}

writeFileSync(
  join(out, "config.js"),
  `/* Generated by scripts/build.mjs at deploy time — do not edit. */\nwindow.MEDLINK_CONFIG = ${JSON.stringify(config, null, 2)};\n`,
);
const rawUrl = env("SUPABASE_URL") || env("NEXT_PUBLIC_SUPABASE_URL");
if (rawUrl && rawUrl.replace(/\/+$/, "") !== config.SUPABASE_URL) console.warn(`⚠  SUPABASE_URL trimmed to ${config.SUPABASE_URL} (was ${rawUrl}).`);
console.log(`✔  Built ${copied} files into dist/ (+ config.js)`);
console.log(`   Supabase: ${config.SUPABASE_URL || "(not set)"} · Clerk key: ${config.CLERK_PUBLISHABLE_KEY ? config.CLERK_PUBLISHABLE_KEY.slice(0, 8) + "…" : "(not set)"}`);
