// Build step for Vercel (no dependencies).
// Copies the static site into dist/ and writes dist/config.js from
// environment variables, so keys never need to be committed.
//
//   CLERK_PUBLISHABLE_KEY, SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY
//
// Run locally with:  node scripts/build.mjs
import { copyFileSync, cpSync, existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "dist");
const SKIP = new Set(["config.js", "config.example.js"]);

rmSync(out, { recursive: true, force: true });
mkdirSync(out);

let copied = 0;
for (const name of readdirSync(root)) {
  if (!/\.(html|css|js|ico|png|svg|webmanifest|txt)$/.test(name) || SKIP.has(name)) continue;
  copyFileSync(join(root, name), join(out, name));
  copied++;
}

// Folders shipped as-is (default site photos).
for (const dir of ["img"]) {
  if (!existsSync(join(root, dir))) continue;
  cpSync(join(root, dir), join(out, dir), { recursive: true });
  copied += readdirSync(join(root, dir)).length;
}

const env = (k) => (process.env[k] || "").trim();
const config = {
  CLERK_PUBLISHABLE_KEY: env("CLERK_PUBLISHABLE_KEY") || env("NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"),
  SUPABASE_URL: env("SUPABASE_URL") || env("NEXT_PUBLIC_SUPABASE_URL"),
  SUPABASE_PUBLISHABLE_KEY:
    env("SUPABASE_PUBLISHABLE_KEY") || env("SUPABASE_ANON_KEY") || env("NEXT_PUBLIC_SUPABASE_ANON_KEY"),
};

const missing = Object.entries(config).filter(([, v]) => !v).map(([k]) => k);
if (missing.length) {
  console.warn(`⚠  Missing environment variables: ${missing.join(", ")}.`);
  console.warn("   The site will deploy, but show a setup screen until they are set in Vercel.");
}
if (/^sk_/.test(config.CLERK_PUBLISHABLE_KEY) || /^sb_secret_/.test(config.SUPABASE_PUBLISHABLE_KEY)) {
  console.error("✖  A SECRET key was provided where a publishable key belongs. Refusing to build.");
  process.exit(1);
}

writeFileSync(
  join(out, "config.js"),
  `/* Generated by scripts/build.mjs at deploy time — do not edit. */\nwindow.MEDLINK_CONFIG = ${JSON.stringify(config, null, 2)};\n`,
);
console.log(`✔  Built ${copied} files into dist/ (+ config.js)`);
